### ISSUE TITLE
Naming of classes

### ISSUE THREAD

**Issue by wouterjdb** [equinor/pypvt#24]
Currently we have 

```
FieldFluidDescription
ElementFluidDescription
BoPVT
```

But what about:

![image](https://user-images.githubusercontent.com/9119793/92246415-000cde00-eec6-11ea-9b0a-1c83485ac2c9.png)

This was a result of a dicussion between me and @anders-kiaer.

What do you think @eivindsm?

**Comment by eivindsm** [comment]
This has now been implemented and merged into master through PR37
