### ISSUE TITLE
License correction

### ISSUE THREAD

**Issue by berland** [equinor/pypvt#31]
pypvt must change to GPLv3, as it depends on GPLv3 ecl2df, which depend on GPLv3 opm-common.

**Comment by eivindsm** [comment]
I believe this has been sorted out. The license file and labeling at github all state GPLv3. Agree?

**Comment by berland** [comment]
No, the `LICENSE` file states "GNU LESSER" in the first line..

**Comment by eivindsm** [comment]
Fixed by https://github.com/equinor/pypvt/pull/32
